name: CI

on:
  push:
    branches: [devel]
  pull_request:

jobs:
  memory:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mm: [refc, orc]

    steps:
      - uses: actions/checkout@v4

      - name: Verify preinstalled toolchain
        run: |
          nim --version
          nimble --version

      - name: Install dependencies
        run: nimble install -y --depsOnly

      - name: Run tests
        run: nim c --mm:${{ matrix.mm }} --path:src -d:test -r tests/tall.nim
